#spring.application.name=ConstructionDrawingManagement
#
#custom.jwt.secret=9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/thangdudai"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true