package com.GSU24SE43.ConstructionDrawingManagement.enums;

public enum Role {
    ADMIN,
    HEAD_OF_ARCHITECTURAL_DESIGN_DEPARTMENT,
    HEAD_OF_STRUCTURAL_DESIGN_DEPARTMENT,
    HEAD_OF_MvE_DESIGN_DEPARTMENT,
    HEAD_OF_INTERIOR_DESIGN_DEPARTMENT,
    DESIGNER,
    COMMANDER
    ;
}
